-- Script Global Solution 2TDSPV 

-- INTEGRANTES: 
-- Carlos E R C Pacheco - RM557323
-- João Pedro Amorim - RM559213
-- Pedro Augusto Ladeira - RM558514

SET DEFINE OFF;

-- 1) Empresa
CREATE TABLE TB_EMPRESA (
	ID_EMPRESA           NUMBER        CONSTRAINT PK_TB_EMPRESA PRIMARY KEY,
	NM_EMPRESA           VARCHAR2(100) NOT NULL,
	DS_CNPJ              VARCHAR2(18),
	DS_POLITICA_HIBRIDA  VARCHAR2(200),
	DT_CADASTRO          DATE          DEFAULT SYSDATE
);

-- 2) Usuario
CREATE TABLE TB_USUARIO (
	ID_USUARIO  NUMBER               CONSTRAINT PK_TB_USUARIO PRIMARY KEY,
	NM_USUARIO  VARCHAR2(100)        NOT NULL,
	DS_EMAIL    VARCHAR2(100)        UNIQUE,
	DS_SENHA    VARCHAR2(100)        NOT NULL,
	TP_USUARIO  CHAR(1)              CONSTRAINT CK_TP_USUARIO CHECK (TP_USUARIO IN ('C','G')),
	DT_CADASTRO DATE                 DEFAULT SYSDATE,
	ST_ATIVO    CHAR(1)              DEFAULT 'S' CONSTRAINT CK_ST_ATIVO CHECK (ST_ATIVO IN ('S','N')),
	ID_EMPRESA  NUMBER               NOT NULL,
	CONSTRAINT FK_TB_USUARIO_TB_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES TB_EMPRESA(ID_EMPRESA)
);

-- 3) Habilidade
CREATE TABLE TB_HABILIDADE (
	ID_HABILIDADE NUMBER            CONSTRAINT PK_TB_HABILIDADE PRIMARY KEY,
	NM_HABILIDADE VARCHAR2(100)    NOT NULL,
	DS_NIVEL      NUMBER(1)         NOT NULL,
	ID_USUARIO    NUMBER            NOT NULL,
	CONSTRAINT FK_TB_HABILIDADE_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

-- 4) Check-in Bem Estar
CREATE TABLE TB_CHECKIN_BEMESTAR (
	ID_CHECKIN    NUMBER           CONSTRAINT PK_TB_CHECKIN PRIMARY KEY,
	ID_USUARIO    NUMBER           NOT NULL,
	VL_HUMOR      NUMBER(1),
	VL_ENERGIA    NUMBER(1),
	VL_ESTRESSE   NUMBER(1),
	DT_CHECKIN    DATE             DEFAULT SYSDATE,
	DS_OBSERVACAO VARCHAR2(200),
	CONSTRAINT FK_TB_CHECKIN_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

-- 5) Tarefa
CREATE TABLE TB_TAREFA (
	ID_TAREFA      NUMBER           CONSTRAINT PK_TB_TAREFA PRIMARY KEY,
	DS_TAREFA      VARCHAR2(150)    NOT NULL,
	DS_AREA        VARCHAR2(50),
	DT_CRIACAO     DATE             DEFAULT SYSDATE,
	ID_GESTOR      NUMBER           NOT NULL,
	ID_COLABORADOR NUMBER,
	ST_TAREFA      VARCHAR2(20) DEFAULT 'Pendente' ,
	CONSTRAINT CK_TB_TAREFA_ST CHECK (ST_TAREFA IN ('Pendente','Em execução','Concluida')),
	CONSTRAINT FK_TB_TAREFA_TB_USUARIO_GESTOR FOREIGN KEY (ID_GESTOR) REFERENCES TB_USUARIO(ID_USUARIO),
	CONSTRAINT FK_TB_TAREFA_TB_USUARIO_COLABORADOR FOREIGN KEY (ID_COLABORADOR) REFERENCES TB_USUARIO(ID_USUARIO)
);

-- 6) Recomendacao IA
CREATE TABLE TB_RECOMENDACAO_IA (
	ID_RECOMENDACAO  NUMBER           CONSTRAINT PK_TB_RECOMENDACAO PRIMARY KEY,
	ID_USUARIO       NUMBER           NOT NULL,
	DS_RECOMENDACAO  VARCHAR2(250),
	DT_RECOMENDACAO  DATE             DEFAULT SYSDATE,
	TP_RECOMENDACAO  VARCHAR2(50),
	CONSTRAINT FK_TB_RECOMENDACAO_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);

-- 7) Log de Atividade
CREATE TABLE TB_LOG_ATIVIDADE (
	ID_LOG     NUMBER           CONSTRAINT PK_TB_LOG PRIMARY KEY,
	ID_USUARIO NUMBER,
	DS_ACAO    VARCHAR2(150),
	DT_ACAO    DATE             DEFAULT SYSDATE,
	ORIGEM     VARCHAR2(50),
	CONSTRAINT FK_TB_LOG_TB_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_USUARIO(ID_USUARIO)
);


CREATE OR REPLACE TRIGGER TRG_TAREFA_VALIDATE_ROLES
BEFORE INSERT OR UPDATE ON TB_TAREFA
FOR EACH ROW
DECLARE
	v_tp TB_USUARIO.TP_USUARIO%TYPE;
BEGIN
	SELECT TP_USUARIO INTO v_tp FROM TB_USUARIO WHERE ID_USUARIO = :NEW.ID_GESTOR;
	IF v_tp <> 'G' THEN
		raise_application_error(-20001, 'ID_GESTOR must reference a user with TP_USUARIO = ''G''');
	END IF;


	IF :NEW.ID_COLABORADOR IS NOT NULL THEN
		SELECT TP_USUARIO INTO v_tp FROM TB_USUARIO WHERE ID_USUARIO = :NEW.ID_COLABORADOR;
		IF v_tp <> 'C' THEN
			raise_application_error(-20002, 'ID_COLABORADOR must reference a user with TP_USUARIO = ''C''');
		END IF;
	END IF;
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		raise_application_error(-20003, 'Referenced user not found for GESTOR/COLABORADOR');
END;
/

COMMIT;

SET DEFINE ON;

-- ==================================================================
-- CRUD procedures (Insert / Update / Delete) para cada tabela
-- ==================================================================

-- TB_EMPRESA
CREATE OR REPLACE PROCEDURE PRC_INSERIR_TB_EMPRESA(
	p_NM_EMPRESA           IN VARCHAR2,
	p_DS_CNPJ              IN VARCHAR2,
	p_DS_POLITICA_HIBRIDA  IN VARCHAR2,
	p_DT_CADASTRO          IN DATE DEFAULT SYSDATE,
	p_ID_EMPRESA           OUT NUMBER
) IS
BEGIN
		p_ID_EMPRESA := SEQ_EMPRESA.NEXTVAL;
	INSERT INTO TB_EMPRESA(ID_EMPRESA, NM_EMPRESA, DS_CNPJ, DS_POLITICA_HIBRIDA, DT_CADASTRO)
	VALUES (p_ID_EMPRESA, p_NM_EMPRESA, p_DS_CNPJ, p_DS_POLITICA_HIBRIDA, p_DT_CADASTRO);
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK;
	RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_TB_EMPRESA(
	p_ID_EMPRESA IN NUMBER,
	p_NM_EMPRESA IN VARCHAR2,
	p_DS_CNPJ IN VARCHAR2,
	p_DS_POLITICA_HIBRIDA IN VARCHAR2
) IS
BEGIN
	UPDATE TB_EMPRESA
	SET NM_EMPRESA = p_NM_EMPRESA,
			DS_CNPJ = p_DS_CNPJ,
			DS_POLITICA_HIBRIDA = p_DS_POLITICA_HIBRIDA
	WHERE ID_EMPRESA = p_ID_EMPRESA;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20010, 'Empresa nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_EXCLUIR_TB_EMPRESA(p_ID_EMPRESA IN NUMBER) IS
BEGIN
	DELETE FROM TB_EMPRESA WHERE ID_EMPRESA = p_ID_EMPRESA;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20011, 'Empresa nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

-- TB_USUARIO
CREATE OR REPLACE PROCEDURE PRC_INSERIR_TB_USUARIO(
	p_NM_USUARIO IN VARCHAR2,
	p_DS_EMAIL IN VARCHAR2,
	p_DS_SENHA IN VARCHAR2,
	p_TP_USUARIO IN CHAR,
	p_ID_EMPRESA IN NUMBER,
	p_ST_ATIVO IN CHAR DEFAULT 'S',
	p_ID_USUARIO OUT NUMBER
) IS
BEGIN
		p_ID_USUARIO := SEQ_USUARIO.NEXTVAL;
	INSERT INTO TB_USUARIO(ID_USUARIO, NM_USUARIO, DS_EMAIL, DS_SENHA, TP_USUARIO, DT_CADASTRO, ST_ATIVO, ID_EMPRESA)
	VALUES(p_ID_USUARIO, p_NM_USUARIO, p_DS_EMAIL, p_DS_SENHA, p_TP_USUARIO, SYSDATE, p_ST_ATIVO, p_ID_EMPRESA);
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_TB_USUARIO(
	p_ID_USUARIO IN NUMBER,
	p_NM_USUARIO IN VARCHAR2,
	p_DS_EMAIL IN VARCHAR2,
	p_DS_SENHA IN VARCHAR2,
	p_TP_USUARIO IN CHAR,
	p_ST_ATIVO IN CHAR,
	p_ID_EMPRESA IN NUMBER
) IS
BEGIN
	UPDATE TB_USUARIO
	SET NM_USUARIO = p_NM_USUARIO,
			DS_EMAIL = p_DS_EMAIL,
			DS_SENHA = p_DS_SENHA,
			TP_USUARIO = p_TP_USUARIO,
			ST_ATIVO = p_ST_ATIVO,
			ID_EMPRESA = p_ID_EMPRESA
	WHERE ID_USUARIO = p_ID_USUARIO;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20020, 'Usuario nao encontrado');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_EXCLUIR_TB_USUARIO(p_ID_USUARIO IN NUMBER) IS
BEGIN
	DELETE FROM TB_USUARIO WHERE ID_USUARIO = p_ID_USUARIO;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20021, 'Usuario nao encontrado');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

-- TB_HABILIDADE
CREATE OR REPLACE PROCEDURE PRC_INSERIR_TB_HABILIDADE(
	p_NM_HABILIDADE IN VARCHAR2,
	p_DS_NIVEL IN NUMBER,
	p_ID_USUARIO IN NUMBER,
	p_ID_HABILIDADE OUT NUMBER
) IS
BEGIN
		p_ID_HABILIDADE := SEQ_HABILIDADE.NEXTVAL;
	INSERT INTO TB_HABILIDADE(ID_HABILIDADE, NM_HABILIDADE, DS_NIVEL, ID_USUARIO)
	VALUES(p_ID_HABILIDADE, p_NM_HABILIDADE, p_DS_NIVEL, p_ID_USUARIO);
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_TB_HABILIDADE(
	p_ID_HABILIDADE IN NUMBER,
	p_NM_HABILIDADE IN VARCHAR2,
	p_DS_NIVEL IN NUMBER
) IS
BEGIN
	UPDATE TB_HABILIDADE
	SET NM_HABILIDADE = p_NM_HABILIDADE,
			DS_NIVEL = p_DS_NIVEL
	WHERE ID_HABILIDADE = p_ID_HABILIDADE;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20030, 'Habilidade nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_EXCLUIR_TB_HABILIDADE(p_ID_HABILIDADE IN NUMBER) IS
BEGIN
	DELETE FROM TB_HABILIDADE WHERE ID_HABILIDADE = p_ID_HABILIDADE;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20031, 'Habilidade nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN
	ROLLBACK; RAISE;
END;
/

-- TB_CHECKIN_BEMESTAR
CREATE OR REPLACE PROCEDURE PRC_INSERIR_TB_CHECKIN_BEMESTAR(
	p_ID_USUARIO IN NUMBER,
	p_VL_HUMOR IN NUMBER,
	p_VL_ENERGIA IN NUMBER,
	p_VL_ESTRESSE IN NUMBER,
	p_DT_CHECKIN IN DATE DEFAULT SYSDATE,
	p_DS_OBSERVACAO IN VARCHAR2,
	p_ID_CHECKIN OUT NUMBER
) IS
BEGIN
		p_ID_CHECKIN := SEQ_CHECKIN.NEXTVAL;
	INSERT INTO TB_CHECKIN_BEMESTAR(ID_CHECKIN, ID_USUARIO, VL_HUMOR, VL_ENERGIA, VL_ESTRESSE, DT_CHECKIN, DS_OBSERVACAO)
	VALUES(p_ID_CHECKIN, p_ID_USUARIO, p_VL_HUMOR, p_VL_ENERGIA, p_VL_ESTRESSE, p_DT_CHECKIN, p_DS_OBSERVACAO);
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_TB_CHECKIN_BEMESTAR(
	p_ID_CHECKIN IN NUMBER,
	p_VL_HUMOR IN NUMBER,
	p_VL_ENERGIA IN NUMBER,
	p_VL_ESTRESSE IN NUMBER,
	p_DS_OBSERVACAO IN VARCHAR2
) IS
BEGIN
	UPDATE TB_CHECKIN_BEMESTAR
	SET VL_HUMOR = p_VL_HUMOR,
			VL_ENERGIA = p_VL_ENERGIA,
			VL_ESTRESSE = p_VL_ESTRESSE,
			DS_OBSERVACAO = p_DS_OBSERVACAO
	WHERE ID_CHECKIN = p_ID_CHECKIN;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20040, 'Checkin nao encontrado');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_EXCLUIR_TB_CHECKIN_BEMESTAR(p_ID_CHECKIN IN NUMBER) IS
BEGIN
	DELETE FROM TB_CHECKIN_BEMESTAR WHERE ID_CHECKIN = p_ID_CHECKIN;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20041, 'Checkin nao encontrado');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

-- TB_TAREFA
CREATE OR REPLACE PROCEDURE PRC_INSERIR_TB_TAREFA(
	p_DS_TAREFA IN VARCHAR2,
	p_DS_AREA IN VARCHAR2,
	p_ID_GESTOR IN NUMBER,
	p_ID_COLABORADOR IN NUMBER DEFAULT NULL,
	p_ST_TAREFA IN VARCHAR2 DEFAULT 'Pendente',
	p_ID_TAREFA OUT NUMBER
) IS
BEGIN
		p_ID_TAREFA := SEQ_TAREFA.NEXTVAL;
	INSERT INTO TB_TAREFA(ID_TAREFA, DS_TAREFA, DS_AREA, DT_CRIACAO, ID_GESTOR, ID_COLABORADOR, ST_TAREFA)
	VALUES(p_ID_TAREFA, p_DS_TAREFA, p_DS_AREA, SYSDATE, p_ID_GESTOR, p_ID_COLABORADOR, p_ST_TAREFA);
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_TB_TAREFA(
	p_ID_TAREFA IN NUMBER,
	p_DS_TAREFA IN VARCHAR2,
	p_DS_AREA IN VARCHAR2,
	p_ID_GESTOR IN NUMBER,
	p_ID_COLABORADOR IN NUMBER,
	p_ST_TAREFA IN VARCHAR2
) IS
BEGIN
	UPDATE TB_TAREFA
	SET DS_TAREFA = p_DS_TAREFA,
			DS_AREA = p_DS_AREA,
			ID_GESTOR = p_ID_GESTOR,
			ID_COLABORADOR = p_ID_COLABORADOR,
			ST_TAREFA = p_ST_TAREFA
	WHERE ID_TAREFA = p_ID_TAREFA;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20050, 'Tarefa nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_EXCLUIR_TB_TAREFA(p_ID_TAREFA IN NUMBER) IS
BEGIN
	DELETE FROM TB_TAREFA WHERE ID_TAREFA = p_ID_TAREFA;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20051, 'Tarefa nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

-- ==================================================================
-- Package PKG_TAREFAS - agrupa operações relacionadas a tarefas
-- ==================================================================
CREATE OR REPLACE PACKAGE PKG_TAREFAS IS
	PROCEDURE INSERIR(p_DS_TAREFA IN VARCHAR2, p_DS_AREA IN VARCHAR2, p_ID_GESTOR IN NUMBER, p_ID_COLABORADOR IN NUMBER, p_ST_TAREFA IN VARCHAR2, p_ID_TAREFA OUT NUMBER);
	PROCEDURE ATUALIZAR(p_ID_TAREFA IN NUMBER, p_DS_TAREFA IN VARCHAR2, p_DS_AREA IN VARCHAR2, p_ID_GESTOR IN NUMBER, p_ID_COLABORADOR IN NUMBER, p_ST_TAREFA IN VARCHAR2);
	PROCEDURE EXCLUIR(p_ID_TAREFA IN NUMBER);
END PKG_TAREFAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_TAREFAS IS
	PROCEDURE INSERIR(p_DS_TAREFA IN VARCHAR2, p_DS_AREA IN VARCHAR2, p_ID_GESTOR IN NUMBER, p_ID_COLABORADOR IN NUMBER, p_ST_TAREFA IN VARCHAR2, p_ID_TAREFA OUT NUMBER) IS
	BEGIN
		PRC_INSERIR_TB_TAREFA(p_DS_TAREFA => p_DS_TAREFA, p_DS_AREA => p_DS_AREA, p_ID_GESTOR => p_ID_GESTOR, p_ID_COLABORADOR => p_ID_COLABORADOR, p_ST_TAREFA => p_ST_TAREFA, p_ID_TAREFA => p_ID_TAREFA);
	END INSERIR;

	PROCEDURE ATUALIZAR(p_ID_TAREFA IN NUMBER, p_DS_TAREFA IN VARCHAR2, p_DS_AREA IN VARCHAR2, p_ID_GESTOR IN NUMBER, p_ID_COLABORADOR IN NUMBER, p_ST_TAREFA IN VARCHAR2) IS
	BEGIN
		PRC_ATUALIZAR_TB_TAREFA(p_ID_TAREFA => p_ID_TAREFA, p_DS_TAREFA => p_DS_TAREFA, p_DS_AREA => p_DS_AREA, p_ID_GESTOR => p_ID_GESTOR, p_ID_COLABORADOR => p_ID_COLABORADOR, p_ST_TAREFA => p_ST_TAREFA);
	END ATUALIZAR;

	PROCEDURE EXCLUIR(p_ID_TAREFA IN NUMBER) IS
	BEGIN
		PRC_EXCLUIR_TB_TAREFA(p_ID_TAREFA => p_ID_TAREFA);
	END EXCLUIR;
END PKG_TAREFAS;
/

-- ==================================================================
-- Package PKG_CHECKINS - agrupa operações de check-in de bem-estar
-- ==================================================================
CREATE OR REPLACE PACKAGE PKG_CHECKINS IS
	PROCEDURE INSERIR(p_ID_USUARIO IN NUMBER, p_VL_HUMOR IN NUMBER, p_VL_ENERGIA IN NUMBER, p_VL_ESTRESSE IN NUMBER, p_DT_CHECKIN IN DATE, p_DS_OBSERVACAO IN VARCHAR2, p_ID_CHECKIN OUT NUMBER);
	PROCEDURE ATUALIZAR(p_ID_CHECKIN IN NUMBER, p_VL_HUMOR IN NUMBER, p_VL_ENERGIA IN NUMBER, p_VL_ESTRESSE IN NUMBER, p_DS_OBSERVACAO IN VARCHAR2);
	PROCEDURE EXCLUIR(p_ID_CHECKIN IN NUMBER);
END PKG_CHECKINS;
/

CREATE OR REPLACE PACKAGE BODY PKG_CHECKINS IS
	PROCEDURE INSERIR(p_ID_USUARIO IN NUMBER, p_VL_HUMOR IN NUMBER, p_VL_ENERGIA IN NUMBER, p_VL_ESTRESSE IN NUMBER, p_DT_CHECKIN IN DATE, p_DS_OBSERVACAO IN VARCHAR2, p_ID_CHECKIN OUT NUMBER) IS
	BEGIN
		PRC_INSERIR_TB_CHECKIN_BEMESTAR(p_ID_USUARIO => p_ID_USUARIO, p_VL_HUMOR => p_VL_HUMOR, p_VL_ENERGIA => p_VL_ENERGIA, p_VL_ESTRESSE => p_VL_ESTRESSE, p_DT_CHECKIN => p_DT_CHECKIN, p_DS_OBSERVACAO => p_DS_OBSERVACAO, p_ID_CHECKIN => p_ID_CHECKIN);
	END INSERIR;

	PROCEDURE ATUALIZAR(p_ID_CHECKIN IN NUMBER, p_VL_HUMOR IN NUMBER, p_VL_ENERGIA IN NUMBER, p_VL_ESTRESSE IN NUMBER, p_DS_OBSERVACAO IN VARCHAR2) IS
	BEGIN
		PRC_ATUALIZAR_TB_CHECKIN_BEMESTAR(p_ID_CHECKIN => p_ID_CHECKIN, p_VL_HUMOR => p_VL_HUMOR, p_VL_ENERGIA => p_VL_ENERGIA, p_VL_ESTRESSE => p_VL_ESTRESSE, p_DS_OBSERVACAO => p_DS_OBSERVACAO);
	END ATUALIZAR;

	PROCEDURE EXCLUIR(p_ID_CHECKIN IN NUMBER) IS
	BEGIN
		PRC_EXCLUIR_TB_CHECKIN_BEMESTAR(p_ID_CHECKIN => p_ID_CHECKIN);
	END EXCLUIR;
END PKG_CHECKINS;
/

-- TB_RECOMENDACAO_IA
CREATE OR REPLACE PROCEDURE PRC_INSERIR_TB_RECOMENDACAO_IA(
	p_ID_USUARIO IN NUMBER,
	p_DS_RECOMENDACAO IN VARCHAR2,
	p_TP_RECOMENDACAO IN VARCHAR2,
	p_ID_RECOMENDACAO OUT NUMBER
) IS
BEGIN
		p_ID_RECOMENDACAO := SEQ_RECOMENDACAO.NEXTVAL;
	INSERT INTO TB_RECOMENDACAO_IA(ID_RECOMENDACAO, ID_USUARIO, DS_RECOMENDACAO, DT_RECOMENDACAO, TP_RECOMENDACAO)
	VALUES(p_ID_RECOMENDACAO, p_ID_USUARIO, p_DS_RECOMENDACAO, SYSDATE, p_TP_RECOMENDACAO);
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_TB_RECOMENDACAO_IA(
	p_ID_RECOMENDACAO IN NUMBER,
	p_DS_RECOMENDACAO IN VARCHAR2,
	p_TP_RECOMENDACAO IN VARCHAR2
) IS
BEGIN
	UPDATE TB_RECOMENDACAO_IA
	SET DS_RECOMENDACAO = p_DS_RECOMENDACAO,
			TP_RECOMENDACAO = p_TP_RECOMENDACAO
	WHERE ID_RECOMENDACAO = p_ID_RECOMENDACAO;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20060, 'Recomendacao nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_EXCLUIR_TB_RECOMENDACAO_IA(p_ID_RECOMENDACAO IN NUMBER) IS
BEGIN
	DELETE FROM TB_RECOMENDACAO_IA WHERE ID_RECOMENDACAO = p_ID_RECOMENDACAO;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20061, 'Recomendacao nao encontrada');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

-- TB_LOG_ATIVIDADE
CREATE OR REPLACE PROCEDURE PRC_INSERIR_TB_LOG_ATIVIDADE(
	p_ID_USUARIO IN NUMBER,
	p_DS_ACAO IN VARCHAR2,
	p_ORIGEM IN VARCHAR2,
	p_ID_LOG OUT NUMBER
) IS
BEGIN
		p_ID_LOG := SEQ_LOG.NEXTVAL;
	INSERT INTO TB_LOG_ATIVIDADE(ID_LOG, ID_USUARIO, DS_ACAO, DT_ACAO, ORIGEM)
	VALUES(p_ID_LOG, p_ID_USUARIO, p_DS_ACAO, SYSDATE, p_ORIGEM);
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_TB_LOG_ATIVIDADE(
	p_ID_LOG IN NUMBER,
	p_DS_ACAO IN VARCHAR2,
	p_ORIGEM IN VARCHAR2
) IS
BEGIN
	UPDATE TB_LOG_ATIVIDADE
	SET DS_ACAO = p_DS_ACAO,
			ORIGEM = p_ORIGEM
	WHERE ID_LOG = p_ID_LOG;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20070, 'Log nao encontrado');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

CREATE OR REPLACE PROCEDURE PRC_EXCLUIR_TB_LOG_ATIVIDADE(p_ID_LOG IN NUMBER) IS
BEGIN
	DELETE FROM TB_LOG_ATIVIDADE WHERE ID_LOG = p_ID_LOG;
	IF SQL%ROWCOUNT = 0 THEN
		raise_application_error(-20071, 'Log nao encontrado');
	END IF;
	COMMIT;
EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/

-- ==================================================================
-- Funções
-- ==================================================================

CREATE OR REPLACE FUNCTION FN_MEDIA_HUMOR_SEMANAL(p_ID_USUARIO IN NUMBER) RETURN NUMBER IS
	v_avg NUMBER;
BEGIN
	SELECT AVG(VL_HUMOR)
	INTO v_avg
	FROM TB_CHECKIN_BEMESTAR
	WHERE ID_USUARIO = p_ID_USUARIO
		AND DT_CHECKIN >= TRUNC(SYSDATE) - 7;
	RETURN NVL(v_avg, 0);
EXCEPTION WHEN NO_DATA_FOUND THEN
	RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_INDICE_BEMESTAR(p_ID_USUARIO IN NUMBER) RETURN NUMBER IS
	v_avg_humor NUMBER;
	v_avg_energia NUMBER;
	v_avg_estresse NUMBER;
	v_index NUMBER;
BEGIN
	SELECT NVL(AVG(VL_HUMOR),0), NVL(AVG(VL_ENERGIA),0), NVL(AVG(VL_ESTRESSE),0)
	INTO v_avg_humor, v_avg_energia, v_avg_estresse
	FROM TB_CHECKIN_BEMESTAR
	WHERE ID_USUARIO = p_ID_USUARIO
		AND DT_CHECKIN >= TRUNC(SYSDATE) - 30; 

	v_index := (v_avg_humor + v_avg_energia + (6 - v_avg_estresse)) / 3;
	RETURN ROUND(v_index,2);
EXCEPTION WHEN NO_DATA_FOUND THEN
	RETURN 0;
END;
/

CREATE OR REPLACE FUNCTION FN_RECOMENDA_COLABORADOR(p_DS_AREA IN VARCHAR2) RETURN NUMBER IS
	v_id NUMBER;
BEGIN
	
	SELECT u.ID_USUARIO
	INTO v_id
	FROM (
		SELECT u.ID_USUARIO,
					 NVL(open_tasks.cnt,0) AS open_cnt,
					 NVL(sk.cnt_skills,0) AS cnt_skills
		FROM TB_USUARIO u
		LEFT JOIN (
			SELECT ID_COLABORADOR, COUNT(*) AS cnt FROM TB_TAREFA WHERE ST_TAREFA <> 'Concluida' GROUP BY ID_COLABORADOR
		) open_tasks ON open_tasks.ID_COLABORADOR = u.ID_USUARIO
		LEFT JOIN (
			SELECT ID_USUARIO, COUNT(*) AS cnt_skills FROM TB_HABILIDADE GROUP BY ID_USUARIO
		) sk ON sk.ID_USUARIO = u.ID_USUARIO
		WHERE u.TP_USUARIO = 'C'
	) u
	WHERE ROWNUM = 1
	ORDER BY u.open_cnt ASC, u.cnt_skills DESC;

	RETURN v_id;
EXCEPTION WHEN NO_DATA_FOUND THEN
	RETURN NULL;
END;
/

CREATE OR REPLACE FUNCTION FN_CONVERTE_JSON_HABILIDADES(p_ID_USUARIO IN NUMBER) RETURN CLOB IS
	v_json CLOB := '[';
	v_first BOOLEAN := TRUE;
BEGIN
	FOR r IN (SELECT NM_HABILIDADE, DS_NIVEL FROM TB_HABILIDADE WHERE ID_USUARIO = p_ID_USUARIO ORDER BY NM_HABILIDADE)
	LOOP
		IF NOT v_first THEN
			v_json := v_json || ',';
		ELSE
			v_first := FALSE;
		END IF;
		v_json := v_json || '{"skill":"' || REPLACE(r.NM_HABILIDADE,'"','\"') || '","nivel":' || r.DS_NIVEL || '}';
	END LOOP;
	v_json := v_json || ']';
	RETURN TO_CLOB(v_json);
EXCEPTION WHEN OTHERS THEN
	RETURN TO_CLOB('[]');
END;
/

-- View: colaboradores mais produtivos (tarefas concluídas nos últimos 30 dias)
	CREATE OR REPLACE VIEW VW_COLABORADORES_PRODUTIVOS AS
	SELECT u.ID_USUARIO,
				 u.NM_USUARIO,
				 COUNT(t.ID_TAREFA) AS TAREFAS_CONCLUIDAS_30D,
				 ROUND(NVL(FN_INDICE_BEMESTAR(u.ID_USUARIO),0),2) AS MEDIA_INDICE_BEMESTAR
	FROM TB_USUARIO u
	LEFT JOIN TB_TAREFA t ON t.ID_COLABORADOR = u.ID_USUARIO
		AND t.ST_TAREFA = 'Concluida'
		AND t.DT_CRIACAO >= TRUNC(SYSDATE) - 30
	WHERE u.TP_USUARIO = 'C'
	GROUP BY u.ID_USUARIO, u.NM_USUARIO;

	-- View: top skills (skills associated with collaborators who completed tasks)
	CREATE OR REPLACE VIEW VW_TOP_SKILLS AS
	SELECT h.NM_HABILIDADE,
				 COUNT(*) AS QTD_USOS
	FROM TB_HABILIDADE h
	JOIN TB_TAREFA t ON t.ID_COLABORADOR = h.ID_USUARIO AND t.ST_TAREFA = 'Concluida'
	GROUP BY h.NM_HABILIDADE;

	-- Procedure: imprime top 3 skills
	CREATE OR REPLACE PROCEDURE PRC_REPORT_TOP_3_SKILLS IS
		CURSOR c_top IS
			SELECT NM_HABILIDADE, QTD_USOS FROM (
				SELECT NM_HABILIDADE, COUNT(*) AS QTD_USOS
				FROM TB_HABILIDADE h
				JOIN TB_TAREFA t ON t.ID_COLABORADOR = h.ID_USUARIO AND t.ST_TAREFA = 'Concluida'
				GROUP BY NM_HABILIDADE
				ORDER BY COUNT(*) DESC
			) WHERE ROWNUM <= 3;
	BEGIN
		DBMS_OUTPUT.PUT_LINE('=== Top 3 Skills mais usadas (base: tarefas concluídas) ===');
		FOR r IN c_top LOOP
			DBMS_OUTPUT.PUT_LINE(r.NM_HABILIDADE || ' - ' || r.QTD_USOS);
		END LOOP;
	END;
	/ 

BEGIN
	DBMS_OUTPUT.PUT_LINE('=== Colaboradores com baixo bem-estar (indice < 3) ===');
END;
/

DECLARE
	CURSOR c_colabs IS
		SELECT ID_USUARIO, NM_USUARIO
		FROM TB_USUARIO
		WHERE TP_USUARIO = 'C';

	v_indice NUMBER;
BEGIN
	FOR r IN c_colabs LOOP
		v_indice := FN_INDICE_BEMESTAR(r.ID_USUARIO);
		IF v_indice < 3 THEN
			DBMS_OUTPUT.PUT_LINE('ID=' || r.ID_USUARIO || ' | Nome=' || r.NM_USUARIO || ' | Indice=' || v_indice);
		END IF;
	END LOOP;
END;
/

-- 2) Gerar relatório semanal de desempenho e tarefas concluídas
DECLARE
	CURSOR c_users IS
		SELECT ID_USUARIO, NM_USUARIO FROM TB_USUARIO;

	v_media_humor NUMBER;
	v_concluidas NUMBER;
BEGIN
	DBMS_OUTPUT.PUT_LINE('=== Relatório Semanal: Desempenho e Tarefas Concluídas (7 dias) ===');
	FOR u IN c_users LOOP
		v_media_humor := FN_MEDIA_HUMOR_SEMANAL(u.ID_USUARIO);
		SELECT COUNT(*) INTO v_concluidas
		FROM TB_TAREFA
		WHERE ID_COLABORADOR = u.ID_USUARIO
			AND ST_TAREFA = 'Concluida'
			AND DT_CRIACAO >= TRUNC(SYSDATE) - 7;

		DBMS_OUTPUT.PUT_LINE('Usuario: ' || u.NM_USUARIO || ' (ID:' || u.ID_USUARIO || ') - MediaHumor7d: ' || NVL(TO_CHAR(v_media_humor), '0') || ' - TarefasConcluidas7d: ' || v_concluidas);
	END LOOP;
END;
/

-- 3) Mostrar recomendações recentes geradas pela IA (últimos 7 dias)
DECLARE
	CURSOR c_rec IS
		SELECT ID_RECOMENDACAO, ID_USUARIO, DS_RECOMENDACAO, DT_RECOMENDACAO, TP_RECOMENDACAO
		FROM TB_RECOMENDACAO_IA
		WHERE DT_RECOMENDACAO >= TRUNC(SYSDATE) - 7
		ORDER BY DT_RECOMENDACAO DESC;
BEGIN
	DBMS_OUTPUT.PUT_LINE('=== Recomendações IA (últimos 7 dias) ===');
	FOR r IN c_rec LOOP
		DBMS_OUTPUT.PUT_LINE('ID:' || r.ID_RECOMENDACAO || ' | Usuário:' || r.ID_USUARIO || ' | Tipo:' || r.TP_RECOMENDACAO || ' | Data:' || TO_CHAR(r.DT_RECOMENDACAO, 'YYYY-MM-DD HH24:MI') );
		DBMS_OUTPUT.PUT_LINE(' Mensagem: ' || r.DS_RECOMENDACAO);
		DBMS_OUTPUT.PUT_LINE('---');
	END LOOP;
END;
/



